<?php

namespace OiLab\OiLaravelChangelogs\Services;

use Carbon\CarbonImmutable;
use DateTimeInterface;
use Illuminate\Contracts\Cache\Repository as CacheRepository;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use OiLab\OiLaravelChangelogs\Data\ChangeLogEntryData;
use OiLab\OiLaravelChangelogs\Data\ChangeLogRowData;
use OiLab\OiLaravelChangelogs\Enums\ChangeLogType;
use OiLab\OiLaravelChangelogs\OiLaravelChangelogs;
use SplFileInfo;
use Symfony\Component\Yaml\Exception\ParseException;
use Symfony\Component\Yaml\Yaml;
use Throwable;

/**
 * The journal of what was fixed and what was improved, read from the
 * repository of the application.
 *
 * No table and no migration: an entry is written in the same pull request as
 * the work it describes, reviewed with it, and deployed with it. A database
 * row would have to be seeded from somewhere, and that somewhere would be
 * these files anyway.
 *
 * The whole directory is parsed to draw one page of the list — there is no
 * index to query — so the parse is cached under a fingerprint of the
 * directory itself. A file added, edited or removed changes the fingerprint
 * and the next read rebuilds; nothing has to be regenerated by hand.
 *
 * Nothing here holds state between requests: the cache is the application's,
 * not a property, so an Octane worker that served yesterday's journal does
 * not keep serving it.
 */
class ChangeLogRepository
{
    public function __construct(private readonly ChangeLogMarkdown $markdown) {}

    /**
     * Every entry, newest first.
     *
     * Ties on the date are broken by the slug, descending: two entries written
     * the same day keep a stable order from one read to the next, which is
     * what the previous / next buttons walk along.
     *
     * @return Collection<int, ChangeLogEntry>
     */
    public function all(): Collection
    {
        /** @var array<int, array<string, mixed>> $cached */
        $cached = $this->cache()->remember(
            'oi-laravel-changelogs.'.$this->fingerprint(),
            $this->ttl(),
            fn (): array => $this->read()->map(
                static fn (ChangeLogEntry $entry): array => [
                    'slug' => $entry->slug,
                    'title' => $entry->title,
                    'date' => $entry->date->toDateString(),
                    'type' => $entry->type->value,
                    'tags' => $entry->tags,
                    'commits' => $entry->commits,
                    'summary' => $entry->summary,
                    'markdown' => $entry->markdown,
                ],
            )->all(),
        );

        return collect($cached)->map(static fn (array $entry): ChangeLogEntry => new ChangeLogEntry(
            slug: (string) $entry['slug'],
            title: (string) $entry['title'],
            date: CarbonImmutable::parse((string) $entry['date']),
            type: ChangeLogType::from((string) $entry['type']),
            tags: array_values(array_map(strval(...), (array) $entry['tags'])),
            commits: array_values(array_map(strval(...), (array) $entry['commits'])),
            summary: (string) $entry['summary'],
            markdown: (string) $entry['markdown'],
        ));
    }

    /**
     * One page of the list, as the paginator the screen draws.
     *
     * @return LengthAwarePaginator<int, ChangeLogRowData>
     */
    public function paginate(int $perPage, int $page, string $path): LengthAwarePaginator
    {
        $entries = $this->all();

        $rows = $entries
            ->slice(($page - 1) * $perPage, $perPage)
            ->map(static fn (ChangeLogEntry $entry): ChangeLogRowData => $entry->toRow())
            ->values();

        return new LengthAwarePaginator(
            items: $rows,
            total: $entries->count(),
            perPage: $perPage,
            currentPage: $page,
            options: ['path' => $path],
        );
    }

    /**
     * The entry a slug names, or null when no file carries it.
     */
    public function find(string $slug): ?ChangeLogEntry
    {
        return $this->all()->first(
            static fn (ChangeLogEntry $entry): bool => $entry->slug === $slug,
        );
    }

    /**
     * The entries either side of one, in the order the list shows them.
     *
     * @return array{previous: ?ChangeLogRowData, next: ?ChangeLogRowData}
     */
    public function adjacent(string $slug): array
    {
        $entries = $this->all()->values();

        $position = $entries->search(
            static fn (ChangeLogEntry $entry): bool => $entry->slug === $slug,
        );

        if ($position === false) {
            return ['previous' => null, 'next' => null];
        }

        return [
            'previous' => $entries->get($position - 1)?->toRow(),
            'next' => $entries->get($position + 1)?->toRow(),
        ];
    }

    /**
     * Render an entry on its way to the reader, in whichever shape the
     * configured engine asked for.
     */
    public function detail(ChangeLogEntry $entry): ChangeLogEntryData
    {
        return $entry->toDetail($this->markdown, OiLaravelChangelogs::rendersOnServer());
    }

    /**
     * Which page of the list an entry sits on.
     */
    public function pageOf(?ChangeLogEntry $entry, int $perPage): int
    {
        if ($entry === null) {
            return 1;
        }

        $position = $this->all()->values()->search(
            static fn (ChangeLogEntry $candidate): bool => $candidate->slug === $entry->slug,
        );

        return $position === false ? 1 : (int) floor($position / $perPage) + 1;
    }

    /**
     * Where the entries are kept.
     */
    public function path(): string
    {
        return OiLaravelChangelogs::path();
    }

    /**
     * Read a frontmatter date, whatever shape yaml handed it back in.
     *
     * Symfony's parser resolves an unquoted `2026-09-12` to a unix timestamp
     * rather than to a string — the yaml spec says a plain scalar matching a
     * timestamp is one — so the obvious `CarbonImmutable::parse((string) $date)`
     * parses "1789084800" and throws. Every entry of the journal writes its
     * date unquoted, so this is the normal path and not the edge case.
     */
    public static function parseDate(mixed $date): ?CarbonImmutable
    {
        if ($date instanceof DateTimeInterface) {
            return CarbonImmutable::instance($date);
        }

        if (is_int($date)) {
            return CarbonImmutable::createFromTimestamp($date, 'UTC');
        }

        if (! is_string($date) || trim($date) === '') {
            return null;
        }

        try {
            return CarbonImmutable::parse(trim($date));
        } catch (Throwable) {
            return null;
        }
    }

    /**
     * A frontmatter list, trimmed, emptied of blanks and of duplicates.
     *
     * Shared by `tags` and `commits`: both are yaml lists of short strings,
     * and both are read by a screen that must not draw an empty badge because
     * somebody left a dangling dash.
     *
     * @return list<string>
     */
    private static function readList(mixed $value): array
    {
        if (! is_array($value)) {
            return [];
        }

        return array_values(array_unique(array_filter(array_map(
            static fn (mixed $item): string => trim((string) (is_scalar($item) ? $item : '')),
            $value,
        ))));
    }

    /**
     * Parse every file of the directory, newest first.
     *
     * A file whose frontmatter is missing, unparseable or incomplete is
     * skipped rather than thrown on: the screen is read by whoever is on call,
     * and a journal that 500s because somebody mistyped a date is worse than a
     * journal missing one entry. `change-log:check` is where a malformed file
     * is named out loud, and it belongs in the test suite.
     *
     * @return Collection<int, ChangeLogEntry>
     */
    private function read(): Collection
    {
        $path = $this->path();

        if (! File::isDirectory($path)) {
            return collect();
        }

        return collect(File::files($path))
            ->filter(static fn (SplFileInfo $file): bool => $file->getExtension() === 'md')
            ->map(fn (SplFileInfo $file): ?ChangeLogEntry => $this->parse($file))
            ->filter()
            ->sortByDesc(static fn (ChangeLogEntry $entry): string => $entry->date->toDateString().'|'.$entry->slug)
            ->values();
    }

    /**
     * One file, or null when it does not carry what an entry needs.
     */
    private function parse(SplFileInfo $file): ?ChangeLogEntry
    {
        $content = File::get($file->getPathname());

        $frontmatter = $this->frontmatter($content);

        if ($frontmatter === null) {
            return null;
        }

        $title = trim((string) ($frontmatter['title'] ?? ''));
        $date = $frontmatter['date'] ?? null;
        $type = ChangeLogType::tryFrom((string) ($frontmatter['type'] ?? ''));

        if ($title === '' || $date === null || $type === null) {
            return null;
        }

        $parsed = static::parseDate($date);

        if ($parsed === null) {
            return null;
        }

        $body = $this->body($content);

        return new ChangeLogEntry(
            slug: $file->getBasename('.md'),
            title: $title,
            date: $parsed,
            type: $type,
            tags: self::readList($frontmatter['tags'] ?? []),
            commits: self::readList($frontmatter['commits'] ?? []),
            summary: $this->summary($body),
            markdown: $body,
        );
    }

    /**
     * The yaml block a file opens with.
     *
     * @return array<string, mixed>|null
     */
    private function frontmatter(string $content): ?array
    {
        if (! str_starts_with($content, '---')) {
            return null;
        }

        $parts = preg_split('/^---$/m', $content, 3);

        if ($parts === false || count($parts) < 3) {
            return null;
        }

        try {
            $parsed = Yaml::parse($parts[1]);
        } catch (ParseException) {
            return null;
        }

        return is_array($parsed) ? $parsed : null;
    }

    /**
     * Everything after the frontmatter.
     */
    private function body(string $content): string
    {
        if (! str_starts_with($content, '---')) {
            return trim($content);
        }

        $parts = preg_split('/^---$/m', $content, 3);

        return trim($parts === false || count($parts) < 3 ? $content : $parts[2]);
    }

    /**
     * The opening paragraph, as one line.
     *
     * This is the description of the problem the format asks for, and it is
     * what the list column shows. Taking it from the body rather than from a
     * frontmatter key means there is one place to write it, and no way for the
     * two to disagree.
     */
    private function summary(string $body): string
    {
        $paragraph = (string) Str::of($body)->before("\n\n")->trim();

        /*
         * A file whose body opens on a heading has no description: rather than
         * show the heading as one, say nothing and let the checker complain.
         */
        if (str_starts_with($paragraph, '#')) {
            return '';
        }

        return (string) Str::of($paragraph)->replaceMatches('/\s+/u', ' ')->trim();
    }

    /**
     * What the directory looks like right now, in one string.
     *
     * Names and modification times: enough for an edit, an addition and a
     * removal to each produce a different key, and cheap enough to compute on
     * every read.
     */
    private function fingerprint(): string
    {
        $path = $this->path();

        if (! File::isDirectory($path)) {
            return 'empty';
        }

        $files = collect(File::files($path))
            ->filter(static fn (SplFileInfo $file): bool => $file->getExtension() === 'md')
            ->map(static fn (SplFileInfo $file): string => $file->getFilename().':'.$file->getMTime())
            ->sort()
            ->implode('|');

        return md5($path.'|'.$files);
    }

    /**
     * The store the parse is kept in.
     */
    private function cache(): CacheRepository
    {
        $store = config('oi-laravel-changelogs.cache.store');

        return Cache::store(is_string($store) && $store !== '' ? $store : null);
    }

    /**
     * How long a parse is kept once the directory has stopped moving.
     *
     * The fingerprint already invalidates on any change, so this only bounds
     * how long a stale entry could survive a clock that went backwards.
     */
    private function ttl(): int
    {
        return max(1, (int) config('oi-laravel-changelogs.cache.ttl', 3600));
    }
}
