/**
 * The journal of what was fixed and what was improved.
 *
 * Two shapes rather than one optional field: the list column carries a row per
 * entry and the right-hand pane carries exactly one, already rendered. Typing
 * the content as optional on a single shape would let a row be handed to the
 * reader and draw nothing, which is the bug this split makes unwritable.
 *
 * Generated by `php artisan change-log:install`. The shapes mirror
 * OiLab\OiLaravelChangelogs\Data\ChangeLogRowData and ChangeLogEntryData.
 */

export type ChangeLogType = 'fix' | 'improvement';

export type ChangeLogRow = {
    /** The file's own name, without its extension: `2026-09-12-the-title`. */
    slug: string;
    title: string;
    /** ISO day, as the frontmatter writes it. */
    date: string;
    type: ChangeLogType;
    /** The translated label of the type, so the badge is not mapped again here. */
    typeLabel: string;
    /**
     * The subjects the entry is filed under, lowercase and hyphenated.
     *
     * Written in the frontmatter and held to that spelling by
     * `change-log:check`: a journal holding "Console" and "console" has two
     * subjects where it means one, and no screen can tell.
     */
    tags: string[];
    /** The commits the entry describes, short hashes. */
    commits: string[];
    /** The opening paragraph, on one line. */
    summary: string;
};

/**
 * One entry, with its content in the shape the configured rendering engine
 * asked for: `html` when the markdown is converted on the server, `markdown`
 * when it is converted in the browser. Exactly one of the two is ever filled.
 */
export type ChangeLogEntry = ChangeLogRow & {
    html: string | null;
    markdown: string | null;
};

/** What the show route answers a fetch with. */
export type ChangeLogAnswer = {
    entry: ChangeLogEntry;
    previous: ChangeLogRow | null;
    next: ChangeLogRow | null;
};

/** The slice of Laravel's paginator the list reads. */
export type ChangeLogPage = {
    data: ChangeLogRow[];
    current_page: number;
    last_page: number;
    total: number;
    prev_page_url: string | null;
    next_page_url: string | null;
};
